{{- if and .Values.istio.enabled .Values.istio.destinationRule.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "makeline-service.fullname" . }}
  labels:
    {{- include "makeline-service.labels" . | nindent 4 }}
spec:
  host: {{ include "makeline-service.fullname" . }}
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        http2MaxRequests: 100
        maxRequestsPerConnection: 2
    loadBalancer:
      simple: LEAST_REQUEST
    outlierDetection:
      consecutiveErrors: 5
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
      minHealthPercent: 40
  subsets:
  - name: stable
    labels:
      {{- include "makeline-service.selectorLabels" . | nindent 6 }}
  - name: canary
    labels:
      {{- include "makeline-service.selectorLabels" . | nindent 6 }}
{{- end }}