apiVersion: v1
kind: Service
metadata:
  name: {{ include "makeline-service.fullname" . }}
  labels:
    {{- include "makeline-service.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.metrics.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.service.port | quote }}
    prometheus.io/path: {{ .Values.metrics.serviceMonitor.path | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "makeline-service.selectorLabels" . | nindent 4 }}