# helm-charts/product-service/values.yaml
replicaCount: 1

image:
  repository: prasad890/store-product-service
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "product-service"

service:
  name: product-service
  type: ClusterIP
  port: 3002
  targetPort: 3002

# Argo Rollouts Strategy
strategy:
  type: canary
  canary:
    steps:
      - setWeight: 20
      - pause:
          duration: 5m
      - analysis:
          templates:
            - templateName: product-service-analysis
      - setWeight: 40
      - pause:
          duration: 5m
      - analysis:
          templates:
            - templateName: product-service-analysis
      - setWeight: 60
      - pause:
          duration: 5m
      - analysis:
          templates:
            - templateName: product-service-analysis
      - setWeight: 80
      - pause:
          duration: 5m
      - analysis:
          templates:
            - templateName: product-service-analysis
      - setWeight: 100

# Istio Configuration
istio:
  enabled: true
  gateway:
    enabled: false
  virtualService:
    enabled: true
    hosts:
      - product-service
  destinationRule:
    enabled: true

# HPA Configuration - FAST SCALING
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 2
          periodSeconds: 15
      selectPolicy: Max
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 3
          periodSeconds: 15
      selectPolicy: Max

# Resource limits
resources:
  requests:
    cpu: 1m
    memory: 50Mi
  limits:
    cpu: 100m
    memory: 256Mi

# Probes - FIXED PORTS
probes:
  startup:
    httpGet:
      path: /health
      port: 3002  # FIXED from 3000
    initialDelaySeconds: 20
    failureThreshold: 5
    periodSeconds: 10
  readiness:
    httpGet:
      path: /health
      port: 3002  # FIXED from 3000
    initialDelaySeconds: 3
    failureThreshold: 3
    periodSeconds: 5
  liveness:
    httpGet:
      path: /health
      port: 3002  # FIXED from 3000
    initialDelaySeconds: 3
    failureThreshold: 5
    periodSeconds: 3

# Environment variables
env:
  - name: AI_SERVICE_URL
    value: "http://ai-service:5001/"

# Vault Configuration - DISABLED
vault:
  enabled: false

# Datadog Configuration
datadog:
  enabled: true
  env: production
  service: product-service
  logs:
    enabled: true
  apm:
    enabled: true
    language: nodejs
  profiling:
    enabled: false

# Prometheus Metrics
metrics:
  enabled: false
  serviceMonitor:
    enabled: false
    interval: 30s
    path: /metrics

# Node selector
nodeSelector:
  kubernetes.io/os: linux

tolerations: []
affinity: {}
podAnnotations: {}
podLabels: {}

# Analysis Template Configuration
analysis:
  enabled: true
  provider: datadog
  datadog:
    secretName: datadog-secret
    metrics:
      - name: error-rate
        query: "avg:trace.http.request.errors{service:product-service,env:production}.as_rate()"
        successCondition: "default(result, 0) < 0.05"
        failureLimit: 3
        interval: 1m
        count: 5
      - name: p95-latency
        query: "avg:trace.http.request.duration.by.service.95p{service:product-service,env:production}"
        successCondition: "default(result, 0) < 1000"
        failureLimit: 3
        interval: 1m
        count: 5

initContainers: []