apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "store-front.fullname" . }}
  labels:
    {{- include "store-front.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "store-front.selectorLabels" . | nindent 6 }}
  strategy:
    {{- if eq .Values.strategy.type "blueGreen" }}
    blueGreen:
      activeService: {{ include "store-front.fullname" . }}
      previewService: {{ include "store-front.fullname" . }}-preview
      autoPromotionEnabled: {{ .Values.strategy.blueGreen.autoPromotionEnabled }}
      {{- if .Values.strategy.blueGreen.autoPromotionSeconds }}
      autoPromotionSeconds: {{ .Values.strategy.blueGreen.autoPromotionSeconds }}
      {{- end }}
      scaleDownDelaySeconds: {{ .Values.strategy.blueGreen.scaleDownDelaySeconds }}
      {{- if .Values.strategy.blueGreen.prePromotionAnalysis }}
      prePromotionAnalysis:
        {{- toYaml .Values.strategy.blueGreen.prePromotionAnalysis | nindent 8 }}
      {{- end }}
      {{- if .Values.strategy.blueGreen.postPromotionAnalysis }}
      postPromotionAnalysis:
        {{- toYaml .Values.strategy.blueGreen.postPromotionAnalysis | nindent 8 }}
      {{- end }}
    {{- end }}
  template:
    metadata:
      labels:
        {{- include "store-front.selectorLabels" . | nindent 8 }}
        {{- include "store-front.datadogLabels" . | nindent 8 }}
        version: {{ .Values.image.tag | quote }}
      annotations:
        {{- if .Values.istio.enabled }}
        sidecar.istio.io/inject: "true"
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "store-front.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        {{- if .Values.datadog.enabled }}
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/service']
        - name: DD_ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/env']
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/version']
        - name: DD_LOGS_INJECTION
          value: "true"
        {{- end }}
        {{- with .Values.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.probes.startup }}
        startupProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.probes.readiness }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.probes.liveness }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}