{{- if and .Values.istio.enabled .Values.istio.virtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "store-front.fullname" . }}
  labels:
    {{- include "store-front.labels" . | nindent 4 }}
spec:
  hosts:
    {{- toYaml .Values.istio.virtualService.hosts | nindent 4 }}
  gateways:
    {{- toYaml .Values.istio.virtualService.gateways | nindent 4 }}
  http:
  {{- range .Values.istio.virtualService.http }}
  - match:
    {{- toYaml .match | nindent 4 }}
    route:
    {{- toYaml .route | nindent 4 }}
  {{- end }}
{{- end }}