# infrastructure/argocd/argocd-notifications-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  slack-token: xoxb-YOUR-SLACK-BOT-TOKEN  # REPLACE with your Slack bot token