#!/bin/bash


export USE_AZURE_OPENAI=False
export USE_AZURE_AD=False
export AZURE_OPENAI_API_VERSION=2024-02-15-preview
export AZURE_OPENAI_DEPLOYMENT_NAME=dall-e-3
export AZURE_OPENAI_ENDPOINT=https://petclinic.openai.azure.com
export AZURE_OPENAI_DALLE_ENDPOINT=https://petclinic.openai.azure.com
export AZURE_OPENAI_DALLE_DEPLOYMENT_NAME=dall-e-3
export OPENAI_API_KEY=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
export OPENAI_ORG_ID=org-MQENs1E0HzS2Bg6rgEc4jkR6
export AZURE_OPENAI_API_KEY=E2jrYMb1QmxMTgxadebnuMAolBK5FT3zjcP1gQ5PhDHaUquD3h5XJQQJ99BEACYeBjFXJ3w3AAABACOG1lXp

echo $USE_AZURE_OPENAI
echo $USE_AZURE_AD
echo $AZURE_OPENAI_API_VERSION
echo $AZURE_OPENAI_DEPLOYMENT_NAME
echo $AZURE_OPENAI_DALLE_ENDPOINT
echo $AZURE_OPENAI_DALLE_DEPLOYMENT_NAME
echo $OPENAI_ORG_ID
echo $OPENAI_API_KEY
echo $AZURE_OPENAI_ENDPOINT


