---
# ===================================================================
# FILE: helm-charts/rabbitmq/values.yaml
# ===================================================================
replicaCount: 1

image:
  repository: mcr.microsoft.com/mirror/docker/library/rabbitmq
  tag: "3.10-management-alpine"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "rabbitmq"

service:
  name: rabbitmq
  type: ClusterIP
  ports:
    amqp:
      port: 5672
      targetPort: 5672
    management:
      port: 15672
      targetPort: 15672
    prometheus:
      port: 15692
      targetPort: 15692

# RabbitMQ authentication
vault:
  enabled: true
  role: "rabbitmq"
  secrets:
    credentials:
      path: "kv/data/rabbitmq"
      template: |
        {{- with secret "kv/data/rabbitmq" -}}
        export RABBITMQ_DEFAULT_USER="{{ .Data.data.username }}"
        export RABBITMQ_DEFAULT_PASS="{{ .Data.data.password }}"
        {{- end -}}

# RabbitMQ authentication (fallback values)
auth:
  username: username
  password: password
  
# RabbitMQ plugins to enable
plugins:
  enabled:
    - rabbitmq_management
    - rabbitmq_prometheus
    - rabbitmq_amqp1_0

# Persistence configuration
persistence:
  enabled: false  # Your original manifest doesn't use persistence
  storageClass: "gp2"
  accessMode: ReadWriteOnce
  size: 5Gi

# Resource limits - matching your standalone manifest
resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

# Prometheus annotations
metrics:
  enabled: true
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "15692"
    prometheus.io/path: "/metrics"

# Node selector
nodeSelector:
  kubernetes.io/os: linux

tolerations: []
affinity: {}
podAnnotations: {}
podLabels: {}
