image:
  repository: prasad890/store-makeline-service
  
service:
  port: 3001
  targetPort: 3001

env:
  - name: ORDER_QUEUE_URI
    value: "amqp://rabbitmq:5672"
  - name: ORDER_QUEUE_USERNAME
    value: "username"
  - name: ORDER_QUEUE_PASSWORD
    value: "password"
  - name: ORDER_QUEUE_NAME
    value: "orders"
  - name: ORDER_DB_URI
    value: "mongodb://mongodb:27017"
  - name: ORDER_DB_NAME
    value: "orderdb"
  - name: ORDER_DB_COLLECTION_NAME
    value: "orders"

datadog:
  service: makeline-service
  apm:
    language: ""  # Golang - limited auto-instrumentation
    enabled: false

# No initContainers
initContainers: []