# helm-charts/virtual-customer/values.yaml
replicaCount: 1

image:
  repository: prasad890/store-virtual-customer
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "virtual-customer"

# No service needed - this is a job/cronjob style workload
service:
  enabled: false

# Standard Deployment - NO Argo Rollouts
strategy:
  type: rolling
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

# No Istio needed for simulator
istio:
  enabled: false

# No HPA needed - fixed replica count
autoscaling:
  enabled: false

# Resource limits
resources:
  requests:
    cpu: 1m
    memory: 1Mi
  limits:
    cpu: 2m
    memory: 20Mi

# No probes - this is a background job
probes:
  enabled: false

# Environment variables
env:
  - name: ORDER_SERVICE_URL
    value: "http://order-service:3000/"
  - name: ORDERS_PER_HOUR
    value: "100"

# Vault Configuration - DISABLED
vault:
  enabled: false

# Datadog Configuration - Basic monitoring only
datadog:
  enabled: true
  env: production
  service: virtual-customer
  version: "{{ .Values.image.tag }}"
  logs:
    enabled: true
  apm:
    enabled: false  # No APM for simulators
  profiling:
    enabled: false

# Node selector
nodeSelector:
  kubernetes.io/os: linux

tolerations: []
affinity: {}
podAnnotations: {}
podLabels: {}